# files
exclude:
  - Makefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - vendor
  - _deprecated

# Markdown
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      category: "Others"

# Site info
url: http://ricostacruz.com/cheatsheets
title: Cheatsheets

# Google analytics
analytics:
  hostname: ricostacruz.com
  id: "UA-20473929-1"

category_names:
  - Ansible
  - Apps
  - CLI
  - CSS
  - Devops
  - Git
  - HTML
  - JavaScript
  - JavaScript libraries
  - Ledger
  - Markup
  - Node.js
  - Rails
  - React
  - Ruby
  - Ruby libraries
  - Vim
  - Others
